// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeHTX-and8cktYH0cahbXVS_ijee4Mu9g',
    appId: '1:565481913499:web:b05f2a02450154f549da3e',
    messagingSenderId: '565481913499',
    projectId: 'edudoor-f6661',
    authDomain: 'edudoor-f6661.firebaseapp.com',
    storageBucket: 'edudoor-f6661.appspot.com',
    measurementId: 'G-F0ZSQGCNPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNaHJM7leOnu7Bjk8JAS28ruZX2nXqPSM',
    appId: '1:565481913499:android:e5f22b01c5eabdae49da3e',
    messagingSenderId: '565481913499',
    projectId: 'edudoor-f6661',
    storageBucket: 'edudoor-f6661.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnScLagWc16qNyW3LzLM6EcZsPC8zHdio',
    appId: '1:565481913499:ios:1798972032d8eac449da3e',
    messagingSenderId: '565481913499',
    projectId: 'edudoor-f6661',
    storageBucket: 'edudoor-f6661.appspot.com',
    iosBundleId: 'com.example.employer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnScLagWc16qNyW3LzLM6EcZsPC8zHdio',
    appId: '1:565481913499:ios:1798972032d8eac449da3e',
    messagingSenderId: '565481913499',
    projectId: 'edudoor-f6661',
    storageBucket: 'edudoor-f6661.appspot.com',
    iosBundleId: 'com.example.employer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeHTX-and8cktYH0cahbXVS_ijee4Mu9g',
    appId: '1:565481913499:web:d2f12696d1abec8d49da3e',
    messagingSenderId: '565481913499',
    projectId: 'edudoor-f6661',
    authDomain: 'edudoor-f6661.firebaseapp.com',
    storageBucket: 'edudoor-f6661.appspot.com',
    measurementId: 'G-KPRBKEKK5C',
  );
}
