import 'package:get/get.dart';

class LocalLanguage extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'title': 'Edudoor Jobseeker',
          'internet_connected': "You're back online!",
          'internet_connected_message': "Stay connected and explore",
          'internet_disconnected': "You're currently offline!",
          'internet_disconnected_message': "Please check your internet connection",
          'copy_right': '@@year Edudoor copyright',
          "login_sign_up": "LOGIN/SIGN UP",
          "get_otp": "GET OTP",
          "benefits": "Benefits",
          'pricing': "Pricing",
          "job_seeker": "Job Seeker",
          'basic_details': "Basic Details",
          "sign_in_with": "or sign in with",
          'enter_phone_number': 'Enter your phone number',
          'welcome': "Welcome",
          'enter_otp': "ENTER OTP",
          'verify_otp': "VERIFY OTP",
          'otp_sent': "We have sent you a OTP of 4 digit on you phone number",
          'resend_otp': "Resend OTP",
          'resend_otp_in': "Resend OTP in @seconds seconds",
          'complete_profile': "Complete profile to apply for job",
          'hr_considers': "HRs only consider consider completed profile",
          'complete_your_profile': "Complete your profile",
          'create_profile': "Create Profile",
          'improve_chance': "Improve your chances of getting shortlisted",
          "add_missing": "Add Missing Details",
          "resume_banner": "Provide a concise summary of your qualification and experience",
          'camera': "Camera",
          "grab_requiters_attention": "Grab Recruiters Attention",
          "guaranteed_interview_calls": "Guaranteed Interview Calls",
          "recommended_by_edudoor": "Recommended by Edudoor",
          'upcoming_events': "Upcoming Events",
          "score_visible": "Score Visible to All Recruiter",
          "get_certified_now": "Get Certified Now",
          'gallery': "Gallery",
          'get_started': "Get Started",
          'upload_image': "Upload Image",
          'upload_resume': "Upload Resume",
          "email_verification": "Verify your email to ensure employers see your application quickly",
          "kyc_verification": "Boost Your Visibility! Verified profiles get noticed faster by potential employers",
          "kyc_now": "KYC Now",
          "kyc": "KYC",
          "verify_now": "Verify Now",
          "add_now": "Add Now",
          'job_preference_details': "Add your job preferences to get job recommendations that match your profile",
          "experience_details": "Add your work experience to grab the attention of potential employers",
          "education_details": "Add your education details to look out of the crowd",
          'name': 'Name',
          'edudoor_certified': "Become Edudoor Certified",
          'email': 'Email',
          'location': "Location",
          "expire_in": "Expire in @time",
          "recommendation": "Recommended Jobs",
          "birthday": "Birthday",
          "resume_service": "Resume Service",
          'gender': "Gender",
          'skip': "Skip",
          'basics': "Basics",
          'education': "Education",
          'experience': "Experience",
          'preference': "Preference",
          'job_preference': "Job Preference",
          'resume': 'resume',
          'next': "Next",
          'save': "Save",
          'home': "Home",
          'Jobs': "Jobs",
          'profile': "Profile",
          'applied': "Applied",
          'course': "Course",
          'search_location': 'Search Location',
          'permission_required': "Permission Required",
          'location_permission_required': 'Enable Location Service Location Permission Required',
          'show_nearby': 'Show You Nearby Places',
          'find_location': 'Enable location to find your location',
          'allow_location': "Allow Location",
          'not_now': "Not Now",
          'email_verified': "Congratulations, your email @email is verified and updated on your account",
          'ok': "OK",
          'verify': 'Verify',
          'email_send_to': 'We have sent you a OTP on @email',
          'verified': "Verified",
        },
      };
}
